In [20]:
function f(x::Integer)
    return (x%5==0) && (x%2==0)
end

f (generic function with 2 methods)

In [1]:
f(5)

LoadError: UndefVarError: f not defined

In [44]:
function g(a,b,c)
   
  #  r1=(-b+sqrt(b**2-4*a*c))/2*a
   #  r2=(-b-sqrt(b**2-4*a*c))/2*a
    dis=b^2-4*a*c
     if dis>=0
        r1=(-b+sqrt(dis))/(2*a)
        r2=(-b-sqrt(dis))/(2*a)
    print("r1=$r1, r2=$r2")
    else
        d=-b/2/a 
        e=sqrt(-dis)/2/a
    print("r1=$d+i$e, r2=$d-i$e")
    end
end


g (generic function with 1 method)

In [50]:
g(1,-1,1)

r1=0.5+i0.8660254037844386, r2=0.5-i0.8660254037844386

In [10]:
function sum_32(N)
    sum = 0
    for i in 1:N
    sum = sum + convert(Float32,1/i)
    end
return sum
end

sum_32 (generic function with 1 method)

In [11]:
sum_32(10000000)

15.403683f0

In [118]:
function sum_64(N)
    sum = 0
    for i in 1:N
    sum = sum + 1/i   ### = sum + convert(Float64,1/i)
    end
return sum
end

sum_64 (generic function with 1 method)

In [119]:
sum_64(10000000)

16.695311365857272

In [94]:
typeof(sum)

LoadError: syntax: extra token "of" after end of expression

In [146]:

function sum_invertida_32(N)
    sum = Float32(0)
    for i in 10000000:-1:N        ### for i in 10_000_000:-1:
    sum = sum + 1/i    
    end
return sum
end

sum_invertida_32 (generic function with 1 method)

In [147]:
sum_invertida_32(1)

16.695311365859965

In [7]:
function sum_invertida_64(N)
    sum = 0
    for i in 10000000:-1:1
    sum = sum + 1/i                ### for i in 10_000_000:-1:1
    end
return sum
end

sum_invertida_64 (generic function with 1 method)

In [8]:
sum_invertida_64(1)

16.695311365859965

In [158]:
# Problema 8

In [173]:
n=4
v=zeros(n)


4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [175]:
n=4
v=ones(n)
v

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [187]:
n=3
v_f = zeros(n,n)
for i in 1:n
        for j in 1:n
            v_f[i,j]=i*j
        end
    end
v_f

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 2.0  4.0  6.0
 3.0  6.0  9.0

In [205]:
n = 2

A = [1 2;3 4]
B = zeros(n,n)
v = ones(n)

for i=1:n
    for j=1:n
        ### B[i]=B[i]+A[i,j]*v[j]   
        B[i] += A[i,j]*v[j]
    end
end
println("$A, $v")

B
        

[1 2; 3 4], [1.0, 1.0]


2×2 Matrix{Float64}:
 3.0  0.0
 7.0  0.0

In [215]:
n = 2

A = [1 2;3 4]
B = zeros(n)
v = ones(n)



for i=1:n
    for j=1:n
        ### B[i] = B[i]+A[i,j]*v[j]   
        B[i] += A[i,j]*v[j]
    end
end
println("$A, $v")

B 
        

[1 2; 3 4], [1.0, 1.0]


2-element Vector{Float64}:
 3.0
 7.0

In [216]:
n = 2

A = [1 2;3 4]
B = zeros(n,n)
v = ones(n)

B = A*v


println("$A, $V")

B 

[1 2; 3 4], [1.0, 1.0]


2-element Vector{Float64}:
 3.0
 7.0

In [269]:
n = 4

A = [1 2;3 4]
B = zeros(n,n)
v = ones(n)

for i=1:n  , j=i+1:n
    B[i,j]=1
end

for i=1:n
   B[i,i]=3
    end
B

4×4 Matrix{Float64}:
 3.0  1.0  1.0  1.0
 0.0  3.0  1.0  1.0
 0.0  0.0  3.0  1.0
 0.0  0.0  0.0  3.0

In [270]:
n = 4

A = [1 2;3 4]
B = zeros(n,n)
v = ones(n)

for i=1:n  , j=i+1:n
    B[i,j]=1
    B[i,i]=3
end
   
B

4×4 Matrix{Float64}:
 3.0  1.0  1.0  1.0
 0.0  3.0  1.0  1.0
 0.0  0.0  3.0  1.0
 0.0  0.0  0.0  0.0

In [279]:
n = 4

A = [1 2;3 4]
B = zeros(n,n)
v = ones(n)

for i=1:n  
    B[i,i+0:n] .= 1 ### operacion punto a punto (a cada termino del vector) Vector .= escalar
    B[i,i]=3
end
   
B

4×4 Matrix{Float64}:
 3.0  1.0  1.0  1.0
 0.0  3.0  1.0  1.0
 0.0  0.0  3.0  1.0
 0.0  0.0  0.0  3.0

In [288]:
n = 5
v = fill(3.,n)    ### v[1:2:n].=3
v[2:2:n].=2
v

5-element Vector{Float64}:
 3.0
 2.0
 3.0
 2.0
 3.0

In [280]:
# Problema 9

In [301]:
i = 0
n = n(i)
function f(n,b)
while n>b
        n = n%b
        i += 1
    end
i    
Nb = zeros(n)
for i=0:b
    Nb[i] = n 
    f(n,b)=n
end
end

f (generic function with 4 methods)

In [12]:
n= 25
b=5

i = 0

while n>b
        n = n%b
        i += 1
    end